//! Trading strategy trait and implementations
//!
//! Defines the interface that all trading strategies must implement.

use crate::models::Candle;
use rust_decimal::Decimal;
use shared::EntryOrderType;
use std::collections::HashMap;

/// Represents a trading signal generated by a strategy
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Signal {
    /// Buy signal (go long)
    Buy,
    /// Sell signal (go short)
    Sell,
    /// No action
    Hold,
    /// Close any open position
    ClosePosition,
}

/// Resolved pending order info, carrying the concrete price from a DataSource.
/// Used at runtime to track pending orders through the engine.
#[derive(Debug, Clone, PartialEq)]
pub struct PendingOrderInfo {
    /// The type of pending order (buy stop, sell stop, buy limit, sell limit)
    pub order_type: EntryOrderType,
    /// The resolved trigger price level
    pub price: Decimal,
    /// Cancel after N bars if not filled (None = no expiry)
    pub expiry_bars: Option<u32>,
}

/// Read-only snapshot of the engine's open position, pushed into strategies
/// once per candle (ABI v5). `None` = flat.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PositionSnapshot {
    /// The actual fill price of the open position.
    pub entry_price: Decimal,
    /// Direction of the open position.
    pub is_long: bool,
}

/// Extended signal with stop loss/take profit levels for risk-based position sizing
#[derive(Debug, Clone)]
pub struct ExtendedSignal {
    pub signal: Signal,
    /// Stop loss price level (if known by the strategy)
    pub stop_loss: Option<Decimal>,
    /// Take profit price level (if known by the strategy)
    pub take_profit: Option<Decimal>,
    /// ID of the entry rule that triggered (for entry signals)
    pub entry_rule_id: Option<String>,
    /// Name of the entry rule (for entry signals)
    pub entry_rule_name: Option<String>,
    /// Reason for exit (for exit signals)
    pub exit_reason: Option<String>,
    /// Indicator values at entry time (flattened: "indicator_id.output" -> value)
    pub entry_indicators: Option<HashMap<String, String>>,
    /// Pending order info (if this signal should create a pending order instead of market entry)
    pub pending_order: Option<PendingOrderInfo>,
}

impl Default for ExtendedSignal {
    fn default() -> Self {
        Self {
            signal: Signal::Hold,
            stop_loss: None,
            take_profit: None,
            entry_rule_id: None,
            entry_rule_name: None,
            exit_reason: None,
            entry_indicators: None,
            pending_order: None,
        }
    }
}

impl From<Signal> for ExtendedSignal {
    fn from(signal: Signal) -> Self {
        Self {
            signal,
            stop_loss: None,
            take_profit: None,
            entry_rule_id: None,
            entry_rule_name: None,
            exit_reason: None,
            entry_indicators: None,
            pending_order: None,
        }
    }
}

/// The trait that all trading strategies must implement
///
/// A strategy receives market data and produces trading signals.
pub trait Strategy {
    /// Prepare the strategy for a backtest run with all candle data.
    /// Called once before the main backtest loop.
    /// This is optional - strategies that need to pre-process data (e.g., detect
    /// price action patterns) should override this method.
    fn prepare(&mut self, _candles: &[Candle]) {
        // Default implementation does nothing
    }

    /// Called for each new candle. Returns a trading signal.
    fn on_candle(&mut self, candle: &Candle) -> Signal;

    /// Called for each new candle. Returns an extended signal with optional SL/TP.
    /// Default implementation wraps on_candle result.
    fn on_candle_extended(&mut self, candle: &Candle) -> ExtendedSignal {
        self.on_candle(candle).into()
    }

    /// Returns the current (potentially trailed) stop loss for the open position
    fn current_stop_loss(&self) -> Option<Decimal> { None }

    /// Returns the current take profit for the open position
    fn current_take_profit(&self) -> Option<Decimal> { None }

    /// Notify the strategy that the engine closed a position externally (e.g. via SL/TP
    /// or end-of-backtest forced close). Strategies that track internal position state
    /// should clear it here so they can evaluate new entries on the next candle.
    fn notify_position_closed(&mut self) {
        // Default: no-op. Strategies without internal position tracking don't need this.
    }

    /// Push the engine's current open-position state into the strategy
    /// (ABI v5). The backtest engine calls this exactly once per candle,
    /// after fills/SL/TP for the candle are settled and immediately before
    /// `on_candle_extended`, so scripts see the truth for the candle they
    /// are evaluating. Hosts that do not simulate positions (live watcher,
    /// `wickd strategy run`) never call it — the ABI v5 accessors then sit
    /// at their flat sentinels.
    fn sync_position_state(&mut self, _position: Option<PositionSnapshot>) {
        // Default: no-op. Strategies without script-visible position state
        // don't need this.
    }

    /// Notify the strategy that a pending entry was rejected at execution time
    /// (e.g. gap between signal and execution candle put the SL on the wrong side).
    /// The strategy generated the signal and may have set internal state (e.g. position
    /// tracking), but no actual trade was opened. Clear that stale state here.
    ///
    /// Separate from `notify_position_closed` because no trade existed — strategies
    /// that use position-close notifications for trade accounting should not treat
    /// a rejected entry the same as a closed position.
    fn notify_entry_rejected(&mut self) {
        // Default: no-op.
    }

    /// Returns the name of this strategy
    fn name(&self) -> &str;

    /// Reset the strategy state (for running multiple backtests)
    fn reset(&mut self);
}

// Example strategy implementations will go here
// e.g., MovingAverageCrossover, RSI, etc.
